class CreateRequests < ActiveRecord::Migration
  def change
    create_table :requests do |t|
      t.boolean :isborrower
      t.boolean :iscoborrower
      t.string :coborroweerRelation
      t.boolean :ismortgagor
      t.string :bName
      t.string :bSName
      t.string :bLName
      t.integer :amount
      t.integer :months
      t.integer :firstAmount
      t.boolean :source_accumulation
      t.boolean :source_sell
      t.boolean :source_help
      t.boolean :source_otherCredit
      t.string :source_other
      t.integer :target
      t.boolean :estate_deposit_new
      t.boolean :estate_deposit_old
      t.integer :estate_deposit_amount
      t.string :region
      t.boolean :military
      t.boolean :mat_cap
      t.boolean :many_children
      t.boolean :russian_family
      t.boolean :aizhk_estate
      t.boolean :apartament
      t.boolean :salary_cred_form
      t.boolean :floatRate
      t.boolean :insurance
      t.integer :seniorityyears
      t.integer :senioritymonths
      t.boolean :emplFixedRecr
      t.boolean :emplFloatRecr
      t.boolean :emplIP
      t.boolean :emplCEO
      t.boolean :emplPensioner
      t.boolean :emplNone
      t.boolean :emplOther
      t.string :emplOtherText
      t.integer :mainWorkYears
      t.integer :mainWorkMonths
      t.string :mainWorkPosition
      t.boolean :mainWorkPosCategoryOwner
      t.boolean :mainWorkPosCategoryGeneral
      t.boolean :mainWorkPosCategoryDepManager
      t.boolean :mainWorkPosCategoryOther
      t.integer :mainWorkAmount
      t.integer :sWorkYears
      t.integer :sWorkMonths
      t.string :sWorkPosition
      t.boolean :sWorkPosCategoryOwner
      t.boolean :sWorkPosCategoryGeneral
      t.boolean :sWorkPosCategoryDepManager
      t.boolean :sWorkPosCategoryOther
      t.integer :sWorkAmount
      t.boolean :otherIncomePension
      t.boolean :otherIncomeLease
      t.boolean :otherIncomeOther
      t.boolean :otherIncomeOtherText
      t.integer :otherIncomeAmount
      t.boolean :expenseAlimony
      t.boolean :expenseAlimonyAmount
      t.boolean :expenseCredit
      t.boolean :estFlat
      t.integer :estFlatPart
      t.boolean :estRoom
      t.integer :estRoomPart
      t.boolean :estHouse
      t.integer :estHousePart
      t.boolean :estOther
      t.string :estOtherTest
      t.integer :estOtherPart
      t.string :estRegion
      t.string :estCity
      t.integer :estPrice
      t.string :carMake
      t.string :carModel
      t.integer :carYear
      t.boolean :carPledge
      t.integer :carPrice
      t.boolean :conviction
      t.boolean :founder
      t.boolean :taxArrears
      t.boolean :otherCreditRequests
      t.boolean :bunkrupt
      t.boolean :waitForChild

      t.timestamps null: false
    end
  end
end
